
//src\lib\appwrite.js
import { Client, Account, Databases, Functions, Storage, Query } from 'appwrite';

const client = new Client();

client
  .setEndpoint(import.meta.env.VITE_APPWRITE_ENDPOINT)
  .setProject(import.meta.env.VITE_APPWRITE_PROJECT_ID);

export const account = new Account(client);
export const databases = new Databases(client);
export const functions = new Functions(client);
export const storage = new Storage(client);
export { Query };

export const DATABASE_ID = import.meta.env.VITE_APPWRITE_DATABASE_ID;
export const DOCUMENTS_BUCKET_ID =
  import.meta.env.VITE_APPWRITE_DOCUMENTS_BUCKET_ID || 'documents';

const COLLECTION_ENV = {
  VITE_APPWRITE_MEMBERS_COLLECTION_ID: import.meta.env.VITE_APPWRITE_MEMBERS_COLLECTION_ID,
  VITE_APPWRITE_SAVINGS_COLLECTION_ID: import.meta.env.VITE_APPWRITE_SAVINGS_COLLECTION_ID,
  VITE_APPWRITE_LOANS_COLLECTION_ID: import.meta.env.VITE_APPWRITE_LOANS_COLLECTION_ID,
  VITE_APPWRITE_LOAN_REPAYMENTS_COLLECTION_ID: import.meta.env.VITE_APPWRITE_LOAN_REPAYMENTS_COLLECTION_ID,
  VITE_APPWRITE_LOAN_CHARGES_COLLECTION_ID: import.meta.env.VITE_APPWRITE_LOAN_CHARGES_COLLECTION_ID,
  VITE_APPWRITE_SUBSCRIPTIONS_COLLECTION_ID: import.meta.env.VITE_APPWRITE_SUBSCRIPTIONS_COLLECTION_ID,
  VITE_APPWRITE_EXPENSES_COLLECTION_ID: import.meta.env.VITE_APPWRITE_EXPENSES_COLLECTION_ID,
  VITE_APPWRITE_UNIT_TRUST_COLLECTION_ID: import.meta.env.VITE_APPWRITE_UNIT_TRUST_COLLECTION_ID,
  VITE_APPWRITE_INTEREST_ALLOCATIONS_COLLECTION_ID: import.meta.env.VITE_APPWRITE_INTEREST_ALLOCATIONS_COLLECTION_ID,
  VITE_APPWRITE_FINANCIAL_CONFIG_COLLECTION_ID: import.meta.env.VITE_APPWRITE_FINANCIAL_CONFIG_COLLECTION_ID,
  VITE_APPWRITE_LEDGER_COLLECTION_ID: import.meta.env.VITE_APPWRITE_LEDGER_COLLECTION_ID,
  VITE_APPWRITE_INTEREST_MONTHLY_COLLECTION_ID: import.meta.env.VITE_APPWRITE_INTEREST_MONTHLY_COLLECTION_ID,
  VITE_APPWRITE_RETAINED_EARNINGS_COLLECTION_ID: import.meta.env.VITE_APPWRITE_RETAINED_EARNINGS_COLLECTION_ID,
  VITE_APPWRITE_LOAN_GUARANTORS_COLLECTION_ID: import.meta.env.VITE_APPWRITE_LOAN_GUARANTORS_COLLECTION_ID,
  VITE_APPWRITE_LOAN_EARLY_REPAYMENTS_COLLECTION_ID: import.meta.env.VITE_APPWRITE_LOAN_EARLY_REPAYMENTS_COLLECTION_ID,
  VITE_APPWRITE_DOCUMENTS_COLLECTION_ID: import.meta.env.VITE_APPWRITE_DOCUMENTS_COLLECTION_ID,
  VITE_APPWRITE_DOCUMENT_CATEGORIES_COLLECTION_ID: import.meta.env.VITE_APPWRITE_DOCUMENT_CATEGORIES_COLLECTION_ID
};

const readCollectionId = (primaryKey, fallbackValue = '') =>
  COLLECTION_ENV[primaryKey] || fallbackValue;

export const COLLECTIONS = {
  MEMBERS: readCollectionId('VITE_APPWRITE_MEMBERS_COLLECTION_ID', '697c8fb200017ff04807'),
  SAVINGS: readCollectionId('VITE_APPWRITE_SAVINGS_COLLECTION_ID', '697c904800100bb6d8ac'),
  LOANS: readCollectionId('VITE_APPWRITE_LOANS_COLLECTION_ID', '697c9171001b85d570c2'),
  LOAN_REPAYMENTS: readCollectionId('VITE_APPWRITE_LOAN_REPAYMENTS_COLLECTION_ID', '697c929c003aedc62d7f'),
  LOAN_CHARGES: readCollectionId('VITE_APPWRITE_LOAN_CHARGES_COLLECTION_ID', '697c9325000805274ae4'),
  SUBSCRIPTIONS: readCollectionId('VITE_APPWRITE_SUBSCRIPTIONS_COLLECTION_ID', '697c9476000289c025df'),
  EXPENSES: readCollectionId('VITE_APPWRITE_EXPENSES_COLLECTION_ID', '697c94ce001de49f1211'),
  UNIT_TRUST: readCollectionId('VITE_APPWRITE_UNIT_TRUST_COLLECTION_ID', '697c956c002816d57a9e'),
  INTEREST_ALLOCATIONS: readCollectionId('VITE_APPWRITE_INTEREST_ALLOCATIONS_COLLECTION_ID', '697c95b9000beba8f806'),
  FINANCIAL_CONFIG: readCollectionId('VITE_APPWRITE_FINANCIAL_CONFIG_COLLECTION_ID', ''),
  LEDGER_ENTRIES: readCollectionId('VITE_APPWRITE_LEDGER_COLLECTION_ID', ''),
  INTEREST_MONTHLY: readCollectionId('VITE_APPWRITE_INTEREST_MONTHLY_COLLECTION_ID', ''),
  RETAINED_EARNINGS: readCollectionId('VITE_APPWRITE_RETAINED_EARNINGS_COLLECTION_ID', ''),
  LOAN_GUARANTORS: readCollectionId('VITE_APPWRITE_LOAN_GUARANTORS_COLLECTION_ID', ''),
  LOAN_EARLY_REPAYMENTS: readCollectionId('VITE_APPWRITE_LOAN_EARLY_REPAYMENTS_COLLECTION_ID', ''),
  DOCUMENTS: readCollectionId('VITE_APPWRITE_DOCUMENTS_COLLECTION_ID', ''),
  DOCUMENT_CATEGORIES: readCollectionId('VITE_APPWRITE_DOCUMENT_CATEGORIES_COLLECTION_ID', '')
};

export default client;
